// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ssi.API.Models;

public partial class CentrosCusto
{
    public uint CentroCustoId { get; set; }

    public string NomeCentroCusto { get; set; }
}