// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ssi.API.Models;

public partial class Historico
{
    public uint HistoricoId { get; set; }

    public DateTime DataAtualizacao { get; set; }

    public string DescricaoAtualizacao { get; set; }

    public int SsiSsiId { get; set; }

    public string UsuarioChapa { get; set; }

    public virtual Ssi SsiSsi { get; set; }

    public virtual Usuario UsuarioChapaNavigation { get; set; }
}