// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ssi.API.Models;

public partial class Servico
{
    public int ServicoId { get; set; }

    public string Mostrar { get; set; }

    public string NomeServico { get; set; }

    public string AreaServico { get; set; }

    public virtual ICollection<Ssi> Ssis { get; set; } = new List<Ssi>();
}