// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ssi.API.Models;

public partial class Ssi
{
    public int SsiId { get; set; }

    public string NomeSolicitante { get; set; }

    public string ChapaSolicitante { get; set; }

    public string CentroDeCusto { get; set; }

    public string Ramal { get; set; }

    public string DescProblema { get; set; }

    public string PatEquipamento { get; set; }

    public DateTime DataRegistro { get; set; }

    public string Andamento { get; set; }

    public DateTime? DataFinalizacao { get; set; }

    public string FkUsuarioChapa { get; set; }

    public int? FkServicoId { get; set; }

    public virtual Usuario ChapaSolicitanteNavigation { get; set; }

    public virtual Servico FkServico { get; set; }

    public virtual Usuario FkUsuarioChapaNavigation { get; set; }

    public virtual ICollection<Historico> Historicos { get; set; } = new List<Historico>();

    public virtual ICollection<Peca> Pecas { get; set; } = new List<Peca>();
}