// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ssi.API.Models;

public partial class ssiContext : DbContext
{
    public ssiContext(DbContextOptions<ssiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CentrosCusto> CentrosCustos { get; set; }

    public virtual DbSet<Historico> Historicos { get; set; }

    public virtual DbSet<Peca> Pecas { get; set; }

    public virtual DbSet<Servico> Servicos { get; set; }

    public virtual DbSet<Ssi> Ssis { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<CentrosCusto>(entity =>
        {
            entity.HasKey(e => e.CentroCustoId).HasName("PRIMARY");
        });

        modelBuilder.Entity<Historico>(entity =>
        {
            entity.HasKey(e => e.HistoricoId).HasName("PRIMARY");

            entity.Property(e => e.UsuarioChapa).IsFixedLength();

            entity.HasOne(d => d.SsiSsi).WithMany(p => p.Historicos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_historico_ssi1");

            entity.HasOne(d => d.UsuarioChapaNavigation).WithMany(p => p.Historicos).HasConstraintName("fk_historico_usuario1");
        });

        modelBuilder.Entity<Peca>(entity =>
        {
            entity.HasKey(e => e.PecaId).HasName("PRIMARY");

            entity.Property(e => e.FkUsuarioChapa).IsFixedLength();

            entity.HasOne(d => d.FkSsi).WithMany(p => p.Pecas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_peca_ssi1");

            entity.HasOne(d => d.FkUsuarioChapaNavigation).WithMany(p => p.Pecas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_peca_usuario1");
        });

        modelBuilder.Entity<Servico>(entity =>
        {
            entity.HasKey(e => e.ServicoId).HasName("PRIMARY");

            entity.Property(e => e.Mostrar).IsFixedLength();
        });

        modelBuilder.Entity<Ssi>(entity =>
        {
            entity.HasKey(e => e.SsiId).HasName("PRIMARY");

            entity.Property(e => e.Andamento).IsFixedLength();
            entity.Property(e => e.ChapaSolicitante).IsFixedLength();
            entity.Property(e => e.FkUsuarioChapa).IsFixedLength();
            entity.Property(e => e.Ramal).IsFixedLength();

            entity.HasOne(d => d.ChapaSolicitanteNavigation).WithMany(p => p.SsiChapaSolicitanteNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_solicitante_chapa");

            entity.HasOne(d => d.FkServico).WithMany(p => p.Ssis).HasConstraintName("fk_ssi_servico1");

            entity.HasOne(d => d.FkUsuarioChapaNavigation).WithMany(p => p.SsiFkUsuarioChapaNavigations).HasConstraintName("fk_ssi_usuario");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Chapa).HasName("PRIMARY");

            entity.Property(e => e.Chapa).IsFixedLength();
            entity.Property(e => e.Mostrar)
                .HasDefaultValueSql("'1'")
                .IsFixedLength();
            entity.Property(e => e.Ramal).IsFixedLength();
            entity.Property(e => e.TipoUsuario).HasDefaultValueSql("'usuario'");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}