// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ssi.API.Models;

public partial class Usuario
{
    public string Chapa { get; set; }

    public string Nome { get; set; }

    public string Ramal { get; set; }

    public string Senha { get; set; }

    public string TipoUsuario { get; set; }

    public string Mostrar { get; set; }

    public string AreaTecnico { get; set; }

    public virtual ICollection<Historico> Historicos { get; set; } = new List<Historico>();

    public virtual ICollection<Peca> Pecas { get; set; } = new List<Peca>();

    public virtual ICollection<Ssi> SsiChapaSolicitanteNavigations { get; set; } = new List<Ssi>();

    public virtual ICollection<Ssi> SsiFkUsuarioChapaNavigations { get; set; } = new List<Ssi>();
}