// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models
{
    [Table("clientes")]
    [Index("Email", Name = "email", IsUnique = true)]
    public partial class Cliente
    {
        public Cliente()
        {
            Emprestimos = new HashSet<Emprestimo>();
        }

        [Key]
        [Column("id_cliente", TypeName = "int(11)")]
        public int IdCliente { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        [Column("telefone")]
        [StringLength(20)]
        public string Telefone { get; set; }
        [Column("data_cadastro")]
        public DateTime DataCadastro { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Emprestimo> Emprestimos { get; set; }
    }
}