// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models
{
    [Table("emprestimos")]
    [Index("IdCliente", Name = "id_cliente")]
    [Index("IdLivro", Name = "id_livro")]
    public partial class Emprestimo
    {
        [Key]
        [Column("id_emprestimo", TypeName = "int(11)")]
        public int IdEmprestimo { get; set; }
        [Column("id_cliente", TypeName = "int(11)")]
        public int? IdCliente { get; set; }
        [Column("id_livro", TypeName = "int(11)")]
        public int? IdLivro { get; set; }
        [Column("data_emprestimo")]
        public DateOnly? DataEmprestimo { get; set; }
        [Column("data_devolucao")]
        public DateOnly? DataDevolucao { get; set; }
        [Column("data_prevista_devolucao")]
        public DateOnly? DataPrevistaDevolucao { get; set; }
        [Column("status", TypeName = "enum('Emprestado','Devolvido')")]
        public string Status { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("Emprestimos")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey("IdLivro")]
        [InverseProperty("Emprestimos")]
        public virtual Livro IdLivroNavigation { get; set; }
    }
}