// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models
{
    [Table("livros")]
    public partial class Livro
    {
        public Livro()
        {
            Emprestimos = new HashSet<Emprestimo>();
        }

        [Key]
        [Column("id_livro", TypeName = "int(11)")]
        public int IdLivro { get; set; }
        [Required]
        [Column("titulo")]
        [StringLength(255)]
        public string Titulo { get; set; }
        [Column("autor")]
        [StringLength(100)]
        public string Autor { get; set; }
        [Column("ano_publicacao", TypeName = "int(11)")]
        public int? AnoPublicacao { get; set; }
        [Column("quantidade", TypeName = "int(11)")]
        public int? Quantidade { get; set; }

        [InverseProperty("IdLivroNavigation")]
        public virtual ICollection<Emprestimo> Emprestimos { get; set; }
    }
}